/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.samistine.inquisitorapi;

/**
 *
 * @author Samuel
 */
public class Statics {

    static final String[] statsParseTags = new String[]{
        "displayName",
        //"        //inventory",
        //"        //armor",
        "heldItemSlot",
        "health",
        "remainingAir",
        "fireTicks",
        "foodLevel",
        "exhaustion",
        "saturation",
        "gameMode",
        "level",
        "exp",
        "totalExperience",
        //"        //potionEffects",
        //"        //server",
        "world",
        "coords",
        //"        //groups",
        "money",
        //"        //bedServer",
        "bedWorld",
        "bedCoords",
        "joins",
        "firstJoin",
        "lastJoin",
        "quits",
        "lastQuit",
        "kicks",
        "lastKick",
        "lastKickMessage",
        "deaths",
        //"        //deathCauses",
        "lastDeath",
        "lastDeathMessage",
        "totalPlayersKilled",
        //"        //playersKilled",
        //"        //playersKilledByWeapon",
        "lastPlayerKill",
        "lastPlayerKilled",
        "totalMobsKilled",
        //"        //mobsKilled",
        //"        //mobsKilledByWeapon",
        "lastMobKill",
        "lastMobKilled",
        "totalBlocksBroken",
        //"        //blocksBroken",
        "totalBlocksPlaced",
        //"        //blocksPlaced",
        //"        //animalsTamed",
        "totalDistanceTraveled",
        "//travelDistances",
        //"        //biomeDistances",
        //"        //travelTimes",
        //"        //biomeTimes",
        "totalItemsDropped",
        //"        //itemsDropped",
        "totalItemsPickedUp",
        //"        //itemsPickedUp",
        "totalItemsCrafted",
        //"        //itemsCrafted",
        //"        //eggsThrown",
        //"        //foodEaten",
        "timesSlept",
        "arrowsShot",
        "firesStarted",
        "fishCaught",
        "chatMessages",
        "portalsCrossed",
        "waterBucketsFilled",
        "waterBucketsEmptied",
        "lavaBucketsFilled",
        "lavaBucketsEmptied",
        "cowsMilked",
        "mooshroomsMilked",
        "mooshroomsSheared",
        "sheepSheared",
        "sheepDyed",
        "lifetimeExperience",
        "itemsEnchanted",
        "itemEnchantmentLevels",
        "sessionTime",
        "totalTime",
        "lastUpdate",
        "online"};

}
